import { assertEquals } from '@std/assert'
import { part2 } from './main.ts'

Deno.test('map has 34 antinodes', () => {
  const input = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`.trim()
  assertEquals(part2(input), 34)
})
