import { assertEquals } from '@std/assert'
import { part1 } from './main.ts'

Deno.test('map has 14 antinodes', () => {
  const input = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`.trim()
  assertEquals(part1(input), 14)
})
