import { assertEquals } from '@std/assert'
import { part2 } from './main.ts'

Deno.test('test is 6', () => {
  const input = `
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`.trim()
  assertEquals(part2(input), 6)
})
